### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by oscarmcm** [bfintal/Counter-Up#14]
Do you have any plan to add support for a package manager such as bower.io ? http://bower.io/docs/creating-packages/

**Comment by mdepecker** [comment]
Counterjs is available with bower

bower install counter-up

if you are using gulp-bower-file or grunt equivalent
you'll have to update your bower.json because main files are not set 

something like this 

"overrides": {
    "counter-up": {
      "main": "*.js"
    }
  }

hope it's help

**Comment by oscarmcm** [comment]
Thanks @mdepecker :+1:
