### ISSUE TITLE
how to stop repeating

### ISSUE THREAD

**Issue by ezatla** [bfintal/Counter-Up#43]
Hi how can we stop its repeating once in counts and it again count the number and decrease the number every time

**Comment by ciromattia** [comment]
It should be fixed in [my fork](https://github.com/ciromattia/jquery.counterup), can you tell me if it's working for you?
Thanks!

**Comment by MichaelJC91** [comment]
Yep :) that fixed it!

**Comment by dardos** [comment]
Perfect ciromattia!

Thanks!
