### ISSUE TITLE
is it possible to add data attribute for delay and time?

### ISSUE THREAD

**Issue by bdthemes** [bfintal/Counter-Up#7]
so we can easily pass separate value from html.

example:
`<span class="counter" data-delay="10" data-time="5000">52,147</span>`

**Comment by ciromattia** [comment]
In [my fork](https://github.com/ciromattia/jquery.counterup) I merged a bunch of PRs - it's already on bower and NPM.
You can get this with:
```
<span class="counter" data-counterup-delay="10" data-counterup-time="5000">52,147</span>
```

**Comment by bdthemes** [comment]
Thanks
